respond_to? should be instance method
javan/whenever pull request #757
Opened 2018-07-16 09:24 UTC by Yuki-Inoue

2018-07-16 20:14 UTC, benlangfeld commented
Could you explain why, and perhaps propose a test to demonstrate how this is broken?

2018-07-18 15:37 UTC, Yuki-Inoue commented
Currently, it does not break anything, as far as I can tell, if the whenever is to be invoked from commandline.

  However, in ruby it is always better to have consistent response between method call and the `respond_to?` method.  Some blog posts explaining this are: http://blog.enriquez.me/2010/2/21/dont-forget-about-respond-to-when-implementing-method-missing/


Actually, I currently have one motivation to fix this; I want to query job_list whether the method identifier is available against this class.

Consider following snippet:

```
bundle exec ruby -I lib -r whenever -r whenever/job_list -e "job_list = Whenever::JobList.new('set :identifier, %(foo)'); puts job_list.respond_to? :identifier; puts job_list.identifier"
```

When executed at top level of this repo, before this fix, it prints:
```
false
foo
```

With this fix, it prints:
```
true
foo
```

  Without this fix, I'd have to actually call `JobList#identifier` in order to determine whether identifier exist, and rescue `NoMethodError` (or, created a method called `identifier_defined?`) for those cases when :identifier is not `set` in the schedule.rb.  Generally, it is not good to use exceptions unless they really are the exceptional cases.

  With this fix, I can determine by just calling `job_list.respond_to? :identifier`.
  (Which is actually done on [here](https://github.com/Yuki-Inoue/whenever/blob/7163abdb3caa4cf12cfe241060049e161067e915/lib/whenever/command_line.rb#L56) on the PR #758)


  P.S. And while I was looking for blogs explaining how respond_to? work, I found we should use `respond_to_missing?` instead of `respond_to?`, as stated in https://stackoverflow.com/questions/13793060/respond-to-vs-respond-to-missing

So, I've fixed it and pushed it to this PR.

2022-12-01 11:20 UTC, KjellMorgenstern commented
irb actually has a problem here.

Start the irb:
```
Running via Spring preloader in process 141262
Loading development environment (Rails 7.0.4)
irb(main):001:0* helper.
```
The moment I type the dot in `helper.` , irb exits with a backtrace:


```
./home/user/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/whenever-1.0.0/lib/whenever/job_list.rb:41:in `respond_to?': undefined method `has_key?' for nil:NilClass (NoMethodError)
                           
      @set_variables.has_key?(name) || super
                    ^^^^^^^^^
        from /home/user/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/completion.rb:364:in `block in retrieve_completion_data'
	from /home/user/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/completion.rb:362:in `each_object'
	from /home/user/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/completion.rb:362:in `retrieve_completion_data'
	from /home/user/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/completion.rb:161:in `block in <module:InputCompletor>'

```

2023-11-13 13:23 UTC, bragamat requested changes
@Yuki-Inoue can you provide some update on this or @benlangfeld can we close this one out ? 😄

2023-11-14 05:56 UTC, Yuki-Inoue commented
Sorry, recently, I don't have much spare time.
I guess this PR can be closed, until someone (or future me, maybe) comes up with test.

2023-11-14 11:56 UTC, bragamat commented
> Sorry, recently, I don't have much spare time. I guess this PR can be closed, until someone (or future me, maybe) comes up with test.

Thank you for the update @Yuki-Inoue!

@benlangfeld let's close this one as well 😄

2023-11-14 13:14 UTC, closed without merging